---
- name: Build RHEL for Edge + Microshift + AWX Operator image
  hosts: rhel8builder
  gather_facts: true
  tasks:
    - name: Create image with microshift
      ansible.builtin.import_role:
        name: edge.microshift.image_builder
      vars:
        microshift_image_custom_repos:
          - name: EPEL8
            base_url: "https://dl.fedoraproject.org/pub/epel/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/Everything/x86_64/"
            type: yum-baseurl
            check_ssl: true
            check_gpg: false
          - name: microshift
            base_url: https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift-testing/epel-8-x86_64/
            type: yum-baseurl
            check_ssl: true
            check_gpg: false
          - name: microshift-deps
            base_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rpms/4.12-el8-beta/
            type: yum-baseurl
            check_ssl: true
            check_gpg: false
          - name: awx-manifest
            base_url: https://download.copr.fedorainfracloud.org/results/maxamillion/microshift-awx-operator-manifest/rhel-8-x86_64/
            type: yum-baseurl
            check_ssl: true
            check_gpg: false
        microshift_image_compose_pkgs:
          - microshift
          - NetworkManager-wifi 
          - microshift-awx-operator-manifests
        microshift_image_compose_type: edge-installer
        microshift_image_pull_secret: "{{ openshift_pull_secret }}"
